[[session]]
name = "Port-Lab"
path = "~/repos/mde/OneCyber.Content/WDATP/Port.Lab/"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "OneCyber-Content"
path = "~/repos/mde/OneCyber.Content/"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "Detection-Resources"
path = "~/repos/mde/Detection.Resources/"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "Detection-ADX-Resources"
path = "~/repos/mde/Detection.ADX.Resources/"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "Port-Runner"
path = "~/repos/mde/Port.Runner/"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "Lensline"
path = "~/repos/personal/lensline.nvim/"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "Dotfiles"
path = "~/.config/dotfiles/"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "proj-opencode"
path = "~/repos/opensource/opencode/"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "scratch"
path = "~/repos/personal/scratch/"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "hippo"
path = "~/repos/personal/hippo/"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "vault-demo"
path = "~/repos/personal/vault-demo/"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "vault-personal"
path = "'/Users/orbarila/Library/Mobile Documents/iCloud~md~obsidian/Documents/personal'"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "vault-work"
path = "/Users/orbarila/Library/CloudStorage/OneDrive-Microsoft/notes_vault/work"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

[[session]]
name = "me"
path = "~/repos/personal/me/"
startup_command = 'tmux send-keys -t 0 "nvim ." C-m \; split-window -h \; split-window -v -t 1 \; send-keys -t 2 "lazygit" C-m'

